hbm_image_delivery_src:
    path:     /%hbm.image_delivery.settings.route%/{format}/{id}/{file}
    defaults: { _controller: HBMImageDeliveryBundle:Default:serveImage, format: null, id: null, file: null }
    requirements:
        file: .+

hbm_video_delivery_src:
    path:     /%hbm.video_delivery.settings.route%/{format}/{id}/{file}
    defaults: { _controller: HBMImageDeliveryBundle:Default:serveVideo, id: null, file: null }
    requirements:
        file: .+
