hbm_image_delivery_src:
    path:     /%hbm.image_delivery.settings.route%/{format}/{id}/{file}
    controller: HBM\MediaDeliveryBundle\Controller\DeliveryController::serveImage
    defaults:
        id:   null
        file: null
        format:   null
    requirements:
        file: .+

hbm_video_delivery_src:
    path:     /%hbm.video_delivery.settings.route%/{id}/{file}
    controller: HBM\MediaDeliveryBundle\Controller\DeliveryController::serveVideo
    defaults:
        id: null
        file: null
    requirements:
        file: .+
