services:
    _defaults:
        public: true

    # HELPER
    hbm.helper.video_delivery:
        class: HBM\MediaDeliveryBundle\Service\VideoDeliveryHelper
        arguments:
            - '%hbm.video_delivery%'
            - '@hbm.helper.sanitizing'
            - '@hbm.helper.hmac'
            - '@router'
            - '@logger'

    hbm.helper.image_delivery:
        class: HBM\MediaDeliveryBundle\Service\ImageDeliveryHelper
        arguments:
            - '%hbm.image_delivery%'
            - '@kernel'
            - '@hbm.command.image_generation'
            - '@hbm.helper.sanitizing'
            - '@hbm.helper.hmac'
            - '@router'
            - '@logger'

    hbm.helper.image_generation:
        class: HBM\MediaDeliveryBundle\Service\ImageGenerationHelper

    # TWIG
    hbm.twig_extensions.image_delivery:
        class: HBM\MediaDeliveryBundle\Twig\ImageDeliveryExtension
        arguments:
            - '@hbm.helper.image_delivery'
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.video_delivery:
        class: HBM\MediaDeliveryBundle\Twig\VideoDeliveryExtension
        arguments:
            - '@hbm.helper.video_delivery'
        tags:
            - { name: twig.extension }

    # CONTROLLER
    HBM\MediaDeliveryBundle\Controller\DeliveryController:
        arguments:
            - '@hbm.helper.image_delivery'
            - '@hbm.helper.video_delivery'
        tags:
            - { name: controller.service_arguments }

    # COMMAND
    hbm.command.image_generation:
        class: HBM\MediaDeliveryBundle\Command\GenerateCommand
        arguments:
            - '%hbm.image_delivery%'
            - '@hbm.helper.image_generation'
            - '@doctrine.orm.entity_manager'
        calls:
            - [setProfiler, ['@?profiler']]
        tags:
            - { name: console.command }

